name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --rm -t test .

      - name: Run Docker container
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        run: |
          docker run --rm -t -v ./:/root/selenium-authenticated-proxy -e PROXY_URL=$PROXY_URL -e PUBLIC_IP=$PUBLIC_IP test bash test.sh
